openapi: 3.0.0
info:
  title: API Key Exposure v1
  version: 1.0.0
paths:
  /data:
    get:
      summary: Get data with API key
      description: This endpoint accepts the API key as a query parameter, which is a security risk as it can be exposed in server logs, browser history, or referrer URLs.
      parameters:
        - name: apiKey
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data returned successfully.