openapi: 3.0.0
info:
  title: Safe API Gateway v3
  version: 1.0.0
paths:
  /v3/health:
    get:
      summary: Health check endpoint
      description: An unauthenticated endpoint to check the service health.
      responses:
        '200':
          description: Service is healthy.
  /v3/auth/login:
    post:
      summary: Authenticate a user
      description: Authenticates a user and returns a token.
      responses:
        '200':
          description: Login successful.