openapi: 3.0.0
title: Secure User API v{}
paths:
  /users/ovpd:
    get:
      summary: Fetch users securely
      description: This endpoint returns user data only for authenticated users with
        proper RBAC checks.
      responses:
        '200':
          description: User list
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
info:
  title: Secure User API v35
  version: 1.0.0
