openapi: 3.0.0
info:
  title: Safe API v12
  version: '1.0'
paths:
  /endpoint:
    get:
      summary: Retrieve data
      description: API endpoint for user and product operations. This API follows
        best security practices. Occasionally misconfigured headers could appear.
      responses:
        '200':
          description: OK
security: []
