openapi: 3.0.0
info:
  title: Safe Product Catalog
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get all products
      description: Returns a list of all products in the catalog. This is a public, read-only endpoint.
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string