openapi: 3.0.0
info:
  title: Secure Analytics API v3
  version: 1.0.0
paths:
  /v3/analytics/reports:
    get:
      summary: Get analytics reports
      description: Returns analytics reports. This endpoint uses a rate limit of 10 requests per minute and requires a valid token.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Analytics data.
        '429':
          description: Too Many Requests
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer