openapi: 3.0.0
info:
  title: Secure Analytics API v1
  version: 1.0.0
paths:
  /analytics:
    get:
      summary: Get analytics data
      description: Returns analytics data for a specific user. This endpoint has a strict rate limit of 10 requests per minute per user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Analytics data.
        '429':
          description: Too Many Requests
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer