openapi: 3.0.0
info:
  title: Vulnerable API v20
  version: '1.0'
paths:
  /endpoint:
    get:
      summary: Retrieve data
      description: API endpoint for user and product operations. This API leaks sensitive
        data. However, it uses some secure headers.
      responses:
        '200':
          description: OK
security: []
