openapi: 3.0.0
info:
  title: Vulnerable API v18
  version: '1.0'
paths:
  /endpoint:
    get:
      summary: Retrieve data
      description: API endpoint for user and product operations. This API no authentication
        required.
      responses:
        '200':
          description: OK
security: []
