openapi: 3.0.0
info:
  title: Vulnerable User API
  version: 1.0.0
paths:
  /users/{id}/role:
    put:
      summary: Update a user's role
      description: This endpoint allows any authenticated user to change the role of any other user using their ID. It lacks proper authorization checks for privilege escalation.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [user, admin]
      responses:
        '200':
          description: Role updated successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer