openapi: 3.0.0
info:
  title: Vulnerable Transaction API v4
  version: 1.0.0
paths:
  /transactions/details/{transactionId}:
    get:
      summary: Get transaction details
      description: Returns details for a transaction. It uses a predictable transaction ID, making it vulnerable to IDOR.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  amount:
                    type: number
                  user:
                    type: string