openapi: 3.0.0
info:
  title: Vulnerable Transaction API v3
  version: 1.0.0
paths:
  /api/v3/transactions/{transactionId}:
    get:
      summary: Get transaction details
      description: Returns details for a transaction. The transaction ID is a simple, incremental string, making it vulnerable to IDOR.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  amount:
                    type: number
                  user:
                    type: string